(()=>{const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const searchInput=document.querySelector("#search,#searchBox");
if(searchInput&&!document.getElementById("orbitSearchToggle")){
 const wrap=searchInput.closest(".search-box,.search");
 if(wrap){
  wrap.classList.add("orbit-search");
  const btn=document.createElement("button");btn.id="orbitSearchToggle";btn.type="button";btn.className="orbit-search-button";btn.setAttribute("aria-label","Open search");btn.innerHTML="<span class=\"orbit-magnifier\"></span>";
  searchInput.classList.add("orbit-search-input");wrap.insertBefore(btn,searchInput);
  const panel=document.createElement("div");panel.id="orbitSearchPanel";panel.className="orbit-search-panel";panel.innerHTML='<div class="orbit-search-title">Collections</div><div class="orbit-collections"><button data-collection="featured">Featured</button><button data-collection="recent">Recently Added</button><button data-collection="watch">Watch Now</button><button data-collection="movies">Movies</button><button data-collection="tv">TV Shows</button></div>';wrap.appendChild(panel);
  const filter=()=>{const q=searchInput.value.trim().toLowerCase();panel.classList.toggle("has-query",!!q);document.querySelectorAll(".movie-card").forEach(card=>card.style.display=!q||card.textContent.toLowerCase().includes(q)?"":"none");};
  btn.onclick=()=>{wrap.classList.toggle("open");if(wrap.classList.contains("open"))searchInput.focus();else{searchInput.value="";filter();}};
  searchInput.addEventListener("input",filter);
  panel.querySelectorAll("[data-collection]").forEach(b=>b.onclick=()=>{const c=b.dataset.collection;wrap.classList.remove("open");if(c==="movies")location.href="/movies.html";else if(c==="tv")location.href="/tv.html";else{const target=c==="featured"?"movies":c==="recent"?"recently-added":c==="watch"?"watch-now":"movies";document.getElementById(target)?.scrollIntoView({behavior:"smooth"});}});
 }
}
const css=document.createElement("style");css.textContent=".orbit-search{position:relative;display:flex;align-items:center}.orbit-search-button{width:42px;height:42px;border:1px solid #333;background:#171717;color:#fff;border-radius:6px;cursor:pointer}.orbit-magnifier{display:inline-block;width:14px;height:14px;border:2px solid currentColor;border-radius:50%;position:relative}.orbit-magnifier:after{content:\"\";position:absolute;width:7px;height:2px;background:currentColor;right:-6px;bottom:-3px;transform:rotate(45deg)}.orbit-search-input{width:0!important;opacity:0;padding:10px 0!important;border:0!important;transition:.25s}.orbit-search.open .orbit-search-input{width:230px!important;opacity:1;padding:10px 14px!important;border:1px solid #333!important;margin-left:8px}.orbit-search-panel{display:none;position:absolute;right:0;top:52px;width:min(680px,90vw);background:#0d0d0d;border:1px solid #2b2b2b;border-radius:10px;padding:16px;box-shadow:0 18px 50px rgba(0,0,0,.65);z-index:500}.orbit-search.open .orbit-search-panel{display:block}.orbit-search-panel.has-query{display:none}.orbit-collections{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.orbit-collections button{height:70px;border:1px solid #333;background:#171717;color:#fff;border-radius:7px;cursor:pointer;font-weight:700}.orbit-collections button:hover{background:#fff;color:#000}@media(max-width:750px){.orbit-search.open .orbit-search-input{width:170px!important}.orbit-collections{grid-template-columns:repeat(2,1fr)}}";document.head.appendChild(css);
(async()=>{try{
 const [cr,sr]=await Promise.all([fetch("/api/public/content",{cache:"no-store"}),fetch("/api/site-settings",{cache:"no-store"})]);
 const cd=cr.ok?await cr.json():{content:[]},sd=sr.ok?await sr.json():{settings:{}},items=cd.content||[],settings=sd.settings||{};
 document.querySelectorAll(".logo").forEach(el=>el.textContent=settings.logo_text||"ORBIT X"); try{const me=await fetch("/api/auth/me",{cache:"no-store"});if(me.ok){const md=await me.json(),p=md.profiles?.[0],av=md.avatars?.find(x=>x.id===p?.avatar_id),nav=document.getElementById("navAvatar");if(nav&&av)nav.innerHTML=av.icon}}catch{}
 const card=i=>{const meta=[i.year,i.rating,i.runtime_minutes?i.runtime_minutes+" min":""].filter(Boolean).join(" · "),url="/watch.html?slug="+encodeURIComponent(i.slug),poster=i.poster_url;return '<article class="movie-card"><div class="poster">'+(poster?'<img src="'+esc(poster)+'" alt="'+esc(i.title)+'" loading="lazy" onerror="this.remove()">':"POSTER")+'</div><div class="movie-info"><div class="movie-title">'+esc(i.title)+'</div><div class="movie-meta">'+esc(meta||"ORBIT")+'</div><a href="'+url+'" class="watch-button">'+esc(settings.watch_button_text||"Watch")+'</a></div></article>'};
 const movies=items.filter(i=>i.type==="movie"),shows=items.filter(i=>i.type==="show"),byId=new Map(items.map(i=>[i.id,i])),pick=(key,fallback)=>{const ids=Array.isArray(settings[key])?settings[key]:[];const chosen=ids.map(x=>byId.get(x)||items.find(i=>i.title===x)).filter(Boolean);return chosen.length?chosen:fallback};
 const featured=pick("featured_ids",movies.filter(i=>i.featured)),recent=pick("recent_ids",movies.slice(0,5)),watchNow=pick("watch_now_ids",movies.slice(0,5)),promo=pick("promo_ids",featured.length?featured:movies.slice(0,6));
 if(location.pathname.endsWith("movies.html")){const g=document.getElementById("movieGrid")||document.querySelector(".movie-grid");if(g)g.innerHTML=movies.map(card).join("")||"<p>No movies published yet.</p>";}
 if(location.pathname.endsWith("tv.html")){const g=document.querySelector(".movie-grid");if(g)g.innerHTML=shows.map(card).join("")||"<p>No TV shows published yet.</p>";}
 if(location.pathname==="/"||location.pathname.endsWith("index.html")){
  const grids=document.querySelectorAll(".movie-grid");if(grids[0])grids[0].innerHTML=featured.map(card).join("")||"<p>No featured movies yet.</p>";if(grids[1])grids[1].innerHTML=recent.map(card).join("")||"<p>No recently added movies yet.</p>";const tv=document.querySelector("#tv .movie-grid");if(tv)tv.innerHTML=shows.slice(0,5).map(card).join("")||"<p>No TV shows published yet.</p>";
  const hero=document.querySelector(".hero"),hi=promo[0];if(hero){const bg=settings.hero_backdrop||(hi&&(hi.backdrop_url||hi.poster_url));if(bg)hero.style.backgroundImage='linear-gradient(90deg,#080808 15%,rgba(8,8,8,.92) 40%,rgba(8,8,8,.45) 75%,rgba(8,8,8,.15)),url("'+String(bg).replace(/"/g,"%22")+'")';const h=hero.querySelector("h1");if(h)h.textContent=settings.hero_title||hi?.title||"ORBIT X";const p=hero.querySelector("p");if(p&&settings.hero_description)p.textContent=settings.hero_description}
  const ad=document.querySelector(".ad-space");if(ad){ad.textContent=settings.ad_enabled===false?"":(settings.ad_text||"ADVERTISEMENT");ad.style.display=settings.ad_enabled===false?"none":""}
  const ts=document.querySelectorAll(".section-title");if(ts[0]&&settings.featured_title)ts[0].textContent=settings.featured_title;if(ts[1]&&settings.recent_title)ts[1].textContent=settings.recent_title;const tvt=document.querySelector("#tv .section-title");if(tvt&&settings.tv_title)tvt.textContent=settings.tv_title;
 }
}catch(e){console.error("ORBIT catalog error",e)}
})();})();